// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: bers_swap_hist.sql

package mariadb

import (
	"context"
	"database/sql"
)

const createBersSwapHistory = `-- name: CreateBersSwapHistory :execresult
INSERT INTO bers_swap_hist(
    sender_tx_hash,
    receiver_tx_hash,
    amount
) VALUES (
    ?,?,?
)
`

type CreateBersSwapHistoryParams struct {
	SenderTxHash   string `json:"sender_tx_hash"`
	ReceiverTxHash string `json:"receiver_tx_hash"`
	Amount         int64  `json:"amount"`
}

func (q *Queries) CreateBersSwapHistory(ctx context.Context, arg CreateBersSwapHistoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBersSwapHistory, arg.SenderTxHash, arg.ReceiverTxHash, arg.Amount)
}

const getBersSwapHistory = `-- name: GetBersSwapHistory :one
SELECT sender_tx_hash, receiver_tx_hash, amount, created_at FROM bers_swap_hist
WHERE sender_tx_hash = ?
`

func (q *Queries) GetBersSwapHistory(ctx context.Context, senderTxHash string) (BersSwapHist, error) {
	row := q.db.QueryRowContext(ctx, getBersSwapHistory, senderTxHash)
	var i BersSwapHist
	err := row.Scan(
		&i.SenderTxHash,
		&i.ReceiverTxHash,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
