name: Build Bridge

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: go version
      - run: go mod tidy
      - run: go build -o ./build/bridge
      - run: cd ./build

      - name: deploy build file via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: bridge
          target: /home/${{ secrets.USERNAME }}/berith-swap/bridge

      - name: start bridge via ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            /home/${{ secrets.USERNAME }}/start_bridge.sh
