name: Build Bridge

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: go version
      - run: go mod tidy
      - run: go build -o bridge

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./bridge"
          target: /home/${{ secrets.USERNAME }}/berith-swap/bridge/bridge

      - name: start bridge
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            /home/${{ secrets.USERNAME }}/start_bridge.sh
